queue_rules:
  - name: default
    queue_conditions:
      - label=automated-bump
    merge_method: squash

pull_request_rules:
  - name: automatic squash merge for version bump
    conditions:
      - label=automated-bump
      - "#approved-reviews-by>=0"
      - check-success=prerelease-app
      - check-success=bump
    actions:
      queue:
        name: default
      delete_head_branch: {}
