import { prisma } from "./prisma";

const SPOTIFY_CLIENT_ID = process.env.SPOTIFY_CLIENT_ID;
const SPOTIFY_CLIENT_SECRET = process.env.SPOTIFY_CLIENT_SECRET;

export async function getCurrentlyPlaying(userId: string) {
    const account = await prisma.account.findFirst({
        where: { userId, providerId: 'spotify' }
    });

    if (!account || !account.refreshToken) return null;

    let accessToken = account.accessToken;

    // Check if token is expired
    if (account.accessTokenExpiresAt && account.accessTokenExpiresAt < new Date()) {
        accessToken = await refreshAccessToken(account.id, account.refreshToken);
    }

    if (!accessToken) return null;

    try {
        const response = await fetch("https://api.spotify.com/v1/me/player/currently-playing", {
            headers: {
                Authorization: `Bearer ${accessToken}`,
            },
        });

        if (response.status === 204 || response.status > 400) {
            return null;
        }

        const data = await response.json();
        if (!data.item) return null;

        return {
            spotifyId: data.item.id,
            name: data.item.name,
            artist: data.item.artists.map((a: any) => a.name).join(", "),
            album: data.item.album.name,
            durationMs: data.item.duration_ms,
            uri: data.item.uri,
            imageUrl: data.item.album.images[0]?.url,
            previewUrl: data.item.preview_url,
        };
    } catch (error) {
        console.error("Error fetching Spotify currently playing:", error);
        return null;
    }
}

async function refreshAccessToken(accountId: string, refreshToken: string) {
    if (!SPOTIFY_CLIENT_ID || !SPOTIFY_CLIENT_SECRET) {
        console.error("Spotify client ID or secret not set");
        return null;
    }

    try {
        const response = await fetch("https://accounts.spotify.com/api/token", {
            method: "POST",
            headers: {
                "Content-Type": "application/x-www-form-urlencoded",
                Authorization: `Basic ${Buffer.from(`${SPOTIFY_CLIENT_ID}:${SPOTIFY_CLIENT_SECRET}`).toString("base64")}`,
            },
            body: new URLSearchParams({
                grant_type: "refresh_token",
                refresh_token: refreshToken,
            }),
        });

        const data = await response.json();

        if (data.error) {
            console.error("Error refreshing Spotify token:", data.error);
            return null;
        }

        const expiresAt = new Date(Date.now() + data.expires_in * 1000);

        await prisma.account.update({
            where: { id: accountId },
            data: {
                accessToken: data.access_token,
                accessTokenExpiresAt: expiresAt,
                refreshToken: data.refresh_token || refreshToken, // Spotify might not return a new refresh token
            },
        });

        return data.access_token;
    } catch (error) {
        console.error("Error refreshing Spotify token:", error);
        return null;
    }
}

export async function createFlowPlaylist(userId: string, trackUris: string[]) {
    const account = await prisma.account.findFirst({
        where: { userId, providerId: 'spotify' }
    });

    if (!account || !account.accessToken) return null;

    let accessToken = account.accessToken;
    if (account.accessTokenExpiresAt && account.accessTokenExpiresAt < new Date()) {
        accessToken = await refreshAccessToken(account.id, account.refreshToken!);
    }

    if (!accessToken) return null;

    try {
        // 1. Get user profile to get user ID for playlist creation
        const profileRes = await fetch("https://api.spotify.com/v1/me", {
            headers: { Authorization: `Bearer ${accessToken}` }
        });
        const profile = await profileRes.json();
        const spotifyUserId = profile.id;

        // 2. Create playlist
        const createRes = await fetch(`https://api.spotify.com/v1/users/${spotifyUserId}/playlists`, {
            method: "POST",
            headers: {
                Authorization: `Bearer ${accessToken}`,
                "Content-Type": "application/json"
            },
            body: JSON.stringify({
                name: "DevMeter Coding Flow",
                description: "Your most productive coding tracks, generated by DevMeter.",
                public: false
            })
        });
        const playlist = await createRes.json();

        // 3. Add tracks
        await fetch(`https://api.spotify.com/v1/playlists/${playlist.id}/tracks`, {
            method: "POST",
            headers: {
                Authorization: `Bearer ${accessToken}`,
                "Content-Type": "application/json"
            },
            body: JSON.stringify({
                uris: trackUris.slice(0, 50) // Max 50 tracks
            })
        });

        return playlist.external_urls.spotify;
    } catch (error) {
        console.error("Error creating Spotify playlist:", error);
        return null;
    }
}
