name: Auto Bump Extension Version

on:
  push:
    branches:
      - main
    paths:
      - 'extension/**'
      - '!extension/package.json'

jobs:
  bump:
    runs-on: ubuntu-latest
    if: github.event.pusher.name != 'github-actions[bot]'
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Bump Version
        working-directory: ./extension
        run: |
          npm version patch --no-git-tag-version

      - name: Create Pull Request for Version Bump
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.AUTO_BUMP_TOKEN || secrets.GITHUB_TOKEN }}
          commit-message: "chore(ext): bump version"
          branch: "auto-bump-extension"
          delete-branch: true
          title: "chore(ext): bump version"
          body: "Automated version bump for the extension."
          labels: "automated-bump"
          add-paths: extension/package.json
